FROM opensearchproject/logstash-oss-with-opensearch-output-plugin:7.0.0

COPY ./elk/logstash/logstash.conf /usr/share/logstash/pipeline/
COPY ./elk/logstash/mysql-connector-java-8.0.28.jar /usr/share/logstash/
