version: '3.7'

services:
  backend:
    image: asia.gcr.io/groomeong-383308/backend:2.8
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.prod

  logstash:
    image: asia.gcr.io/groomeong-383308/logstash:1.3
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.logstash
